import { parseExperiencedEnvelope } from '@/lib/experiencedReport/parse'
import type { ExperiencedReportEnvelope } from '@/lib/experiencedReport/types'

/** Simulated in-home box report for godough.co embeds. Not a client study. */
const MARKETING_BOX_REPORT_RAW = {
  status: 'ok',
  is_simulated: true,
  report_id: 'marketing-box-report',
  mission_id: 'marketing-box-1',
  brand_id: 1,
  focal_product_id: 1,
  snapshot_date: '2026-09-18',
  computed_at: '2026-09-18T16:00:00Z',
  is_current: true,
  report: {
    focal_product: {
      product_id: 1,
      name: 'Keel Lemon Water',
      brand: 'Keel',
    },
    participation: {
      n_users: 64,
      n_claims: 64,
      n_sessions: 118,
    },
    report_stage: {
      stage: 'final',
      is_final: true,
      mission_status: 'complete',
      target_completions: 80,
      completions_delivered: 64,
      stage_semantics: 'Final report — fielding closed.',
    },
    reliability: {
      reportable: true,
      value: 0.78,
      ci_low: 0.68,
      ci_high: 0.86,
      withheld_reason: null,
      consistency_rate: 0.78,
      n_users_with_repeats: 42,
      scope_note: 'Consistency among people who repeated a decisive choice.',
    },
    headline_win_rate: [
      {
        reportable: true,
        value: 0.58,
        ci_low: 0.5,
        ci_high: 0.66,
        n_decisive: 96,
        experience_split: 'experienced_vs_experienced',
        withheld_reason: null,
      },
    ],
      per_opponent: [
        {
          opponent_product_id: 11,
          opponent_name: 'Rivermark Citrus Still',
          opponent_brand: 'Rivermark',
          reportable: true,
          value: 0.62,
          ci_low: 0.5,
          ci_high: 0.73,
          n_decisive: 48,
          n_wins: 30,
          experience_split: 'experienced_vs_experienced',
          withheld_reason: null,
        },
        {
          opponent_product_id: 12,
          opponent_name: 'Northveil Lemon',
          opponent_brand: 'Northveil',
          reportable: true,
          value: 0.54,
          ci_low: 0.42,
          ci_high: 0.66,
          n_decisive: 48,
          n_wins: 26,
          experience_split: 'experienced_vs_experienced',
          withheld_reason: null,
        },
      ],
    choice_drivers: {
      by_outcome: {
        focal_won: [
          {
            driver: 'Taste',
            share: 0.38,
            reportable: true,
            value: 0.38,
            ci_low: null,
            ci_high: null,
            withheld_reason: null,
          },
          {
            driver: 'Clean finish',
            share: 0.24,
            reportable: true,
            value: 0.24,
            ci_low: null,
            ci_high: null,
            withheld_reason: null,
          },
        ],
        focal_lost: [
          {
            driver: 'Price',
            share: 0.41,
            reportable: true,
            value: 0.41,
            ci_low: null,
            ci_high: null,
            withheld_reason: null,
          },
          {
            driver: 'Familiarity',
            share: 0.22,
            reportable: true,
            value: 0.22,
            ci_low: null,
            ci_high: null,
            withheld_reason: null,
          },
        ],
      },
      timing_note:
        'Choices after people had the product at home — not a shelf glance.',
      presentation_control: 'Same pack art and price frame for every session.',
    },
    attribute_importance: {
      attributes: [
        {
          attribute: 'Taste',
          bw_score: 0.34,
          reportable: true,
          value: 0.34,
          ci_low: null,
          ci_high: null,
          withheld_reason: null,
        },
        {
          attribute: 'Value',
          bw_score: 0.12,
          reportable: true,
          value: 0.12,
          ci_low: null,
          ci_high: null,
          withheld_reason: null,
        },
        {
          attribute: 'Packaging',
          bw_score: -0.08,
          reportable: true,
          value: -0.08,
          ci_low: null,
          ci_high: null,
          withheld_reason: null,
        },
      ],
    },
    repurchase_intent: {
      by_session: [
        {
          session_number: 1,
          metric: 'definite_yes',
          rate: 0.47,
          reportable: true,
          value: 0.47,
          ci_low: 0.35,
          ci_high: 0.59,
          withheld_reason: null,
        },
        {
          session_number: 1,
          metric: 'top_two_box',
          rate: 0.72,
          reportable: true,
          value: 0.72,
          ci_low: null,
          ci_high: null,
          withheld_reason: null,
        },
        {
          session_number: 1,
          metric: 'no',
          rate: 0.14,
          reportable: true,
          value: 0.14,
          ci_low: null,
          ci_high: null,
          withheld_reason: null,
        },
        {
          session_number: 2,
          metric: 'definite_yes',
          rate: 0.41,
          reportable: true,
          value: 0.41,
          ci_low: 0.28,
          ci_high: 0.55,
          withheld_reason: null,
        },
        {
          session_number: 2,
          metric: 'top_two_box',
          rate: 0.66,
          reportable: true,
          value: 0.66,
          ci_low: null,
          ci_high: null,
          withheld_reason: null,
        },
      ],
    },
    rank_validation: {
      by_pair_class: [
        {
          pair_class: 'battled',
          reportable: true,
          agreement_rate: 0.71,
          value: 0.71,
          ci_low: 0.58,
          ci_high: 0.82,
          n_agree: 34,
          n_disagree: 14,
          n_determinate: 48,
          withheld_reason: null,
        },
      ],
    },
    experience_lift_vs_baseline: {
      reportable: true,
      value: 3.4,
      mean_elo_delta: 3.4,
      ci_low: 0.8,
      ci_high: 6.1,
      withheld_reason: null,
    },
    ihut_core: {
      version: 'IHUT_CORE_V1',
      taste_only: false,
      success_bars: {
        taste_win_share: 0.55,
        liking_share: 0.6,
        buy_at_price_share: 0.55,
      },
      verdict: {
        ref: 1,
        name: 'Keel Lemon Water',
        overall: 'too_close_to_call',
        taste_win: {
          share: 0.64,
          n: 64,
          wins: 41,
          lo: 0.56,
          hi: 0.72,
          bar: 0.55,
          result: 'cleared',
        },
        liking: {
          share: 0.72,
          n: 64,
          lo: 0.61,
          hi: 0.81,
          bar: 0.6,
          result: 'cleared',
        },
        buy_at_price: {
          share: 0.61,
          n: 64,
          lo: 0.49,
          hi: 0.72,
          bar: 0.55,
          result: 'too_close_to_call',
        },
      },
      promise_vs_delivery: {
        shelf: [
          { ref: 12, name: 'Northveil Lemon', rank: 1, strength: 0.72 },
          {
            ref: 1,
            name: 'Keel Lemon Water',
            rank: 2,
            strength: 0.61,
            is_yours: true,
          },
          { ref: 11, name: 'Rivermark Citrus Still', rank: 3, strength: 0.48 },
        ],
        taste: [
          {
            ref: 1,
            name: 'Keel Lemon Water',
            rank: 1,
            strength: 0.78,
            is_yours: true,
          },
          { ref: 11, name: 'Rivermark Citrus Still', rank: 2, strength: 0.59 },
          { ref: 12, name: 'Northveil Lemon', rank: 3, strength: 0.43 },
        ],
        map: [
          {
            ref: 1,
            name: 'Keel Lemon Water',
            is_yours: true,
            shelf_strength: 0.61,
            taste_strength: 0.78,
          },
        ],
        note: 'Shelf promise is compared with the tasted experience in the same field.',
      },
      liking: [
        { ref: 1, name: 'Keel Lemon Water', n: 64, top_two_share: 0.72 },
        { ref: 11, name: 'Rivermark Citrus Still', n: 64, top_two_share: 0.64 },
        { ref: 12, name: 'Northveil Lemon', n: 64, top_two_share: 0.58 },
      ],
      price_check: [
        {
          ref: 1,
          name: 'Keel Lemon Water',
          n: 64,
          yes_share: 0.61,
          maybe_share: 0.22,
          no_share: 0.17,
          lo: 0.49,
          hi: 0.72,
          tested_price_dollars: 3.49,
          reportable: true,
          decision_ready: true,
        },
        {
          ref: 11,
          name: 'Rivermark Citrus Still',
          n: 64,
          yes_share: 0.66,
          maybe_share: 0.2,
          no_share: 0.14,
          lo: 0.54,
          hi: 0.76,
          tested_price_dollars: 2.99,
          reportable: true,
          decision_ready: true,
        },
        {
          ref: 12,
          name: 'Northveil Lemon',
          n: 64,
          yes_share: 0.63,
          maybe_share: 0.21,
          no_share: 0.16,
          lo: 0.51,
          hi: 0.74,
          tested_price_dollars: 3.29,
          reportable: true,
          decision_ready: true,
        },
      ],
      price_intent: {
        analysis_version: 'IHUT_PRICE_V2',
        label: 'tested_offer_intent',
        interpretation:
          "Stated willingness to buy at each product's frozen shelf price after tasting. Not demand, elasticity, conversion, or an optimal price.",
        price_check_enabled: true,
        descriptive_floor: 10,
        decision_floor: 30,
        tested_prices: [
          {
            ref: 1,
            name: 'Keel Lemon Water',
            is_yours: true,
            price_dollars: 3.49,
          },
          {
            ref: 11,
            name: 'Rivermark Citrus Still',
            is_yours: false,
            price_dollars: 2.99,
          },
          {
            ref: 12,
            name: 'Northveil Lemon',
            is_yours: false,
            price_dollars: 3.29,
          },
        ],
        day1: [
          {
            ref: 1,
            name: 'Keel Lemon Water',
            n: 64,
            yes_share: 0.61,
            maybe_share: 0.22,
            no_share: 0.17,
            yes_n: 39,
            maybe_n: 14,
            no_n: 11,
            lo: 0.49,
            hi: 0.72,
            tested_price_dollars: 3.49,
            reportable: true,
            decision_ready: true,
          },
          {
            ref: 11,
            name: 'Rivermark Citrus Still',
            n: 64,
            yes_share: 0.66,
            maybe_share: 0.2,
            no_share: 0.14,
            lo: 0.54,
            hi: 0.76,
            tested_price_dollars: 2.99,
            reportable: true,
            decision_ready: true,
          },
          {
            ref: 12,
            name: 'Northveil Lemon',
            n: 64,
            yes_share: 0.63,
            maybe_share: 0.21,
            no_share: 0.16,
            lo: 0.51,
            hi: 0.74,
            tested_price_dollars: 3.29,
            reportable: true,
            decision_ready: true,
          },
        ],
        day2: [
          {
            ref: 1,
            name: 'Keel Lemon Water',
            n: 44,
            yes_share: 0.55,
            maybe_share: 0.25,
            no_share: 0.2,
            lo: 0.4,
            hi: 0.69,
            tested_price_dollars: 3.49,
            reportable: true,
            decision_ready: true,
          },
        ],
        day1_to_day2: [
          {
            ref: 1,
            name: 'Keel Lemon Water',
            n_paired: 40,
            improved_share: 0.1,
            worsened_share: 0.18,
            stable_share: 0.72,
            reportable: true,
            matrix: {
              yes_yes: 18,
              yes_maybe: 4,
              yes_no: 2,
              maybe_yes: 3,
              maybe_maybe: 7,
              maybe_no: 2,
              no_yes: 1,
              no_maybe: 1,
              no_no: 2,
            },
          },
        ],
        value_leakage: [
          {
            ref: 1,
            name: 'Keel Lemon Water',
            n_first: 33,
            n_first_but_no_at_price: 7,
            share: 0.212,
            reportable: true,
          },
        ],
      },
      price_check_enabled: true,
      analysis_version: 'REPORT_V2',
      attribute_penalties: [
        {
          ref: 1,
          name: 'Keel Lemon Water',
          attribute: 'lemon_intensity',
          attribute_label: 'Lemon intensity',
          n: 64,
          too_little_share: 0.11,
          just_right_share: 0.73,
          too_much_share: 0.16,
        },
        {
          ref: 11,
          name: 'Rivermark Citrus Still',
          attribute: 'lemon_intensity',
          attribute_label: 'Lemon intensity',
          n: 64,
          too_little_share: 0.22,
          just_right_share: 0.58,
          too_much_share: 0.2,
        },
        {
          ref: 12,
          name: 'Northveil Lemon',
          attribute: 'lemon_intensity',
          attribute_label: 'Lemon intensity',
          n: 64,
          too_little_share: 0.06,
          just_right_share: 0.51,
          too_much_share: 0.43,
        },
        {
          ref: 1,
          name: 'Keel Lemon Water',
          attribute: 'sweetness',
          attribute_label: 'Sweetness',
          n: 64,
          too_little_share: 0.08,
          just_right_share: 0.64,
          too_much_share: 0.28,
        },
        {
          ref: 11,
          name: 'Rivermark Citrus Still',
          attribute: 'sweetness',
          attribute_label: 'Sweetness',
          n: 64,
          too_little_share: 0.14,
          just_right_share: 0.71,
          too_much_share: 0.15,
        },
        {
          ref: 12,
          name: 'Northveil Lemon',
          attribute: 'sweetness',
          attribute_label: 'Sweetness',
          n: 64,
          too_little_share: 0.19,
          just_right_share: 0.55,
          too_much_share: 0.26,
        },
        {
          ref: 1,
          name: 'Keel Lemon Water',
          attribute: 'aftertaste',
          attribute_label: 'Aftertaste',
          n: 64,
          too_little_share: 0.09,
          just_right_share: 0.78,
          too_much_share: 0.13,
        },
        {
          ref: 11,
          name: 'Rivermark Citrus Still',
          attribute: 'aftertaste',
          attribute_label: 'Aftertaste',
          n: 64,
          too_little_share: 0.12,
          just_right_share: 0.66,
          too_much_share: 0.22,
        },
        {
          ref: 12,
          name: 'Northveil Lemon',
          attribute: 'aftertaste',
          attribute_label: 'Aftertaste',
          n: 64,
          too_little_share: 0.05,
          just_right_share: 0.49,
          too_much_share: 0.46,
        },
        {
          ref: 1,
          name: 'Keel Lemon Water',
          attribute: 'carbonation',
          attribute_label: 'Carbonation',
          n: 64,
          too_little_share: 0.18,
          just_right_share: 0.69,
          too_much_share: 0.13,
        },
        {
          ref: 11,
          name: 'Rivermark Citrus Still',
          attribute: 'carbonation',
          attribute_label: 'Carbonation',
          n: 64,
          too_little_share: 0.31,
          just_right_share: 0.62,
          too_much_share: 0.07,
        },
        {
          ref: 12,
          name: 'Northveil Lemon',
          attribute: 'carbonation',
          attribute_label: 'Carbonation',
          n: 64,
          too_little_share: 0.1,
          just_right_share: 0.57,
          too_much_share: 0.33,
        },
      ],
      expectation_vs_experience: [
        {
          ref: 1,
          name: 'Keel Lemon Water',
          n: 64,
          liked_and_expected_good_share: 0.69,
        },
        {
          ref: 11,
          name: 'Rivermark Citrus Still',
          n: 64,
          liked_and_expected_good_share: 0.55,
        },
        {
          ref: 12,
          name: 'Northveil Lemon',
          n: 64,
          liked_and_expected_good_share: 0.41,
        },
      ],
      buy_order: [
        {
          ref: 1,
          name: 'Keel Lemon Water',
          n: 64,
          first_share: 0.52,
          avg_rank: 1.64,
        },
        {
          ref: 11,
          name: 'Rivermark Citrus Still',
          n: 64,
          first_share: 0.3,
          avg_rank: 2.05,
        },
        {
          ref: 12,
          name: 'Northveil Lemon',
          n: 64,
          first_share: 0.18,
          avg_rank: 2.31,
        },
      ],
      taste_why: [
        { answer: 'Bright, natural lemon flavor', n: 27 },
        { answer: 'Clean finish', n: 19 },
        { answer: 'Not too sweet', n: 13 },
        { answer: 'Refreshing without being sharp', n: 11 },
        { answer: 'Tastes like real lemon, not candy', n: 9 },
        { answer: 'Light enough to drink every day', n: 8 },
        { answer: 'Refreshing carbonation', n: 5 },
        { answer: 'No artificial aftertaste', n: 4 },
        { answer: 'Balanced acidity', n: 3 },
      ],
      day2: {
        preference_hold: { n: 44, same_favorite_share: 0.68 },
        consumption: [
          { answer: 'Finished it', n: 25 },
          { answer: 'More than half', n: 13 },
          { answer: 'Half or less', n: 6 },
        ],
        wear: [
          { answer: 'Grew on me', n: 14 },
          { answer: 'Felt the same', n: 24 },
          { answer: 'Wore off', n: 6 },
        ],
        price_check: [
          {
            ref: 1,
            name: 'Keel Lemon Water',
            n: 44,
            yes_share: 0.55,
            maybe_share: 0.25,
            no_share: 0.2,
            lo: 0.4,
            hi: 0.69,
            tested_price_dollars: 3.49,
            reportable: true,
            decision_ready: true,
          },
        ],
      },
    },
    methodology: {
      multiple_comparison_note:
        'Opponents are reported separately. Do not average win rates across the shelf.',
    },
  },
}

export function marketingBoxReportEnvelope(): ExperiencedReportEnvelope | null {
  return parseExperiencedEnvelope(MARKETING_BOX_REPORT_RAW, 'marketing-box-1')
}

/** Thin IHUT evidence: price checks off, no Day 2 price, small field. */
export function marketingBoxReportThinEnvelope(): ExperiencedReportEnvelope | null {
  const rich = structuredClone(MARKETING_BOX_REPORT_RAW) as Record<string, unknown>
  const report = rich.report as Record<string, unknown>
  const core = report.ihut_core as Record<string, unknown>
  core.price_check_enabled = false
  core.price_check = []
  core.price_intent = {
    analysis_version: 'IHUT_PRICE_V2',
    label: 'tested_offer_intent',
    interpretation:
      "Stated willingness to buy at each product's frozen shelf price after tasting. Not demand, elasticity, conversion, or an optimal price.",
    price_check_enabled: false,
    descriptive_floor: 10,
    decision_floor: 30,
    tested_prices: [],
    day1: [],
    day2: [],
    day1_to_day2: [],
    value_leakage: [],
  }
  core.day2 = {
    preference_hold: { n: 0, same_favorite_share: null },
    consumption: [],
    wear: [],
    price_check: [],
  }
  const verdict = core.verdict as Record<string, unknown>
  verdict.buy_at_price = {
    share: null,
    n: 0,
    lo: null,
    hi: null,
    bar: null,
    result: 'not_tested',
  }
  verdict.overall = 'cleared'
  return parseExperiencedEnvelope(rich, 'marketing-box-thin')
}
